list=[2,3,4,5,6]
list.append(7)
print("appended list:",list)
list.extend([8,9])
print("extended list:",list)    
list.insert(3,11)
print("inserted list:",list)
list.remove(4)
print("removed list:",list)
list.pop(2)
print("popped list:",list)
list.sort()
print("sorted list:",list)
list.clear()
print("cleared list:",list)