mark=(50, 60, 70, 80, 90)
print ("tuple:",mark)
print ("length of tuple:",len(mark))
print ("max of tuple:",max(mark))
print ("min of tuple:",min(mark))
print ("sum of tuple:",sum(mark))
print ("count of 70 in tuple:",mark.count(70))
print ("index of 80 in tuple:",mark.index(80))
print ("sliced tuple:",mark[1:4])
print ("reversed tuple:",mark[::-1])
print ("tuple after concatenation:",mark+(100,110))
print ("tuple after repetition:",mark*2)
print("reverse index:",mark[-1])
print("tuple after slicing:",mark[1:5])
print("tuple after slicing with step:",mark[::2])